// 包含了多个mutation的type
export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_CATEGORYS = 'receive_categorys'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_USER = 'receive_user'
export const RECEIVE_TOKEN = 'receive_token'
export const RESET_USER = 'reset_user'
export const RESET_TOKEN = 'reset_token'
export const RECEIVE_GOODS = 'receive_goods'
export const RECEIVE_RATINGS = 'receive_ratings'
export const RECEIVE_INFO = 'receive_info'
export const ADD_FOOD_COUNT='add_food_count'
export const REDUCE_FOOD_COUNT='reduce_food_count'
