// 包含了多个直接修改状态数据的方法的对象
// import { RECEIVE_ADDRESS, RECEIVE_CATEGORYS, RECEIVE_SHOPS, RECEIVE_USER, RECEIVE_TOKEN, RESET_USER, RESET_TOKEN, RECEIVE_GOODS, RECEIVE_RATINGS, RECEIVE_INFO } from './mutation-types'
export default {
}